services:
  - type: web
    name: lead-generator-pro
    env: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4 